version: "3"
services:
    nginx:
        image: steveltn/https-portal:1
        links:
            - php7
            - gitbucket
        ports:
            - 80:80
            - 443:443
        restart: always
        environment:
            STAGE: staging
            DOMAINS: 'noyu.cf, k2.noyu.cf, git.noyu.cf -> http://gitbucket:8080, dir.noyu.cf'
            SERVER_NAMES_HASH_BUCKET_SIZE: 64
        volumes:
            - ./data/cert:/var/lib/https-portal
            - ./nginx/conf:/var/lib/nginx-conf:ro
            - ./nginx/html:/var/www/html
            - owncloud:/var/www/owncloud

    php7:
        image: php:7-fpm-alpine
        restart: always
        volumes:
            - ./nginx/html:/var/www/html
            - owncloud:/var/www/owncloud
            - ./data/owncloud/data:/mnt/data
        command: sh -c 'apk add shadow && addgroup -g 1001 owncloud && usermod -aG owncloud www-data'

    gitbucket:
        image: gitbucket/gitbucket
        restart: always
        volumes:
            - ./data/gitbucket/data:/gitbucket
        links:
            - gitbucket-postgres
        environment:
            GITBUCKET_DB_URL: 'jdbc:postgresql://gitbucket-postgres/gitbucket'
            GITBUCKET_DB_USER: gitbucket
            GITBUCKET_DB_PASSWORD: ${GITBUCKET_DB_PASSWORD}

    gitbucket-postgres:
        build: gitbucket/postgres
        restart: always
        volumes:
            - ./data/gitbucket/postgres:/var/lib/postgresql/data
            - ./gitbucket/postgres/init:/docker-entrypoint-initdb.d
        environment:
            POSTGRES_USER: postgres
            DB_PASSWORD: ${GITBUCKET_DB_PASSWORD}

    owncloud:
        image: owncloud/server:10.0
        links:
            - owncloud-mariadb
            - redis
        environment:
            OWNCLOUD_DOMAIN: dir.noyu.cf
            OWNCLOUD_DB_TYPE: mysql
            OWNCLOUD_DB_HOST: owncloud-mariadb
            OWNCLOUD_DB_NAME: owncloud
            OWNCLOUD_DB_USERNAME: owncloud
            OWNCLOUD_DB_PASSWORD: ${OWNCLOUD_DB_PASSWORD}
            OWNCLOUD_REDIS_ENABLED: "true"
            OWNCLOUD_REDIS_HOST: redis
        volumes:
            - ./data/owncloud/data:/mnt/data
            # for nginx
            - owncloud:/var/www/owncloud

    owncloud-mariadb:
        image: mariadb:10
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${OWNCLOUD_DB_PASSWORD}
            MYSQL_USER: owncloud
            MYSQL_PASSWORD: ${OWNCLOUD_DB_PASSWORD}
            MYSQL_DATABASE: owncloud
        volumes:
            - ./data/owncloud/mariadb:/var/lib/mysql
            - ./data/owncloud/mariadb-backup:/var/lib/backup

    redis:
        image: redis:5-alpine
        restart: always
 
volumes:
    owncloud:


