version: "3"
services:
    nginx:
        image: steveltn/https-portal:1
        links:
            - php7
            - gitbucket
        ports:
            - 80:80
            - 443:443
        restart: always
        environment:
            STAGE: staging
            DOMAINS: 'noyu.cf, k2.noyu.cf, git.noyu.cf -> http://gitbucket:8080'
            SERVER_NAMES_HASH_BUCKET_SIZE: 64
        volumes:
            - ./data/cert:/var/lib/https-portal
            - ./nginx/conf:/var/lib/nginx-conf:ro
            - ./nginx/html:/var/www/html
            - owncloud:/var/www/owncloud
    php7:
        image: php:7-fpm-alpine
        restart: always
        volumes:
            - ./nginx/html:/var/www/html
    gitbucket:
        image: gitbucket/gitbucket
        restart: always
        volumes:
            - ./data/gitbucket/data:/gitbucket
        ports:
            - 8080:8080
        links:
            - gitbucket-postgres
        environment:
            GITBUCKET_DB_URL: 'jdbc:postgresql://gitbucket-postgres/gitbucket'
            GITBUCKET_DB_USER: gitbucket
            GITBUCKET_DB_PASSWORD: ${POSTGRES_GITBUCKET_PASSWORD}

    gitbucket-postgres:
        build: gitbucket/postgres
        restart: always
        volumes:
            - ./data/gitbucket/postgres:/var/lib/postgresql/data
            - ./gitbucket/postgres/init:/docker-entrypoint-initdb.d
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_GITBUCKET_PASSWORD: ${POSTGRES_GITBUCKET_PASSWORD}

    owncloud:
        image: owncloud/server:10.0
        links:
            - owncloud-postgres
        environment:
            OWNCLOUD_DOMAIN: dir.noyu.cf
            OWNCLOUD_DB_TYPE: pgsql
            OWNCLOUD_DB_HOST: owncloud-postgres
            OWNCLOUD_DB_NAME: owncloud
            OWNCLOUD_DB_USERNAME: owncloud
            OWNCLOUD_DB_PASSWORD: ${POSTGRES_OWNCLOUD_PASSWORD}
        volumes:
            - ./data/owncloud/data:/mnt/data
            # for nginx
            - owncloud:/var/www/owncloud

    owncloud-postgres:
        build: owncloud/postgres
        restart: always
        volumes:
            - ./data/owncloud/postgres:/var/lib/postgresql/data
            - ./owncloud/postgres/init:/docker-entrypoint-initdb.d
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_OWNCLOUD_PASSWORD: ${POSTGRES_OWNCLOUD_PASSWORD}

volumes:
    owncloud:


