version: "3"
services:
    nginx:
        image: steveltn/https-portal:1
        links:
            - php7
            - gitbucket
            - owncloud
            - wekan
        ports:
            - 80:80
            - 443:443
        restart: always
        environment:
            STAGE: staging
            DOMAINS: >
                noyu.cf,
                k2.noyu.cf,
                git.noyu.cf -> http://gitbucket:8080,
                dir.noyu.cf -> http://owncloud:8080, 
                board.noyu.cf -> http://wekan:8080
            SERVER_NAMES_HASH_BUCKET_SIZE: 64
        volumes:
            - ./data/cert:/var/lib/https-portal
            - ./nginx/conf:/var/lib/nginx-conf:ro
            - ./nginx/html:/var/www/vhosts

    php7:
        image: php:7-fpm-alpine
        restart: always
        volumes:
            - ./nginx/html:/var/www/html

    gitbucket:
        image: gitbucket/gitbucket
        restart: always
        volumes:
            - ./data/gitbucket/data:/gitbucket
        links:
            - gitbucket-db
        environment:
            GITBUCKET_DB_URL: 'jdbc:postgresql://gitbucket-postgres/gitbucket'
            GITBUCKET_DB_USER: gitbucket
            GITBUCKET_DB_PASSWORD: ${GITBUCKET_DB_PASSWORD}

    gitbucket-db:
        build: gitbucket/postgres
        restart: always
        volumes:
            - ./data/gitbucket/postgres:/var/lib/postgresql/data
            - ./gitbucket/postgres/init:/docker-entrypoint-initdb.d
        environment:
            POSTGRES_USER: postgres
            DB_PASSWORD: ${GITBUCKET_DB_PASSWORD}

    owncloud:
        image: owncloud/server:latest
        links:
            - owncloud-db
            - redis
        environment:
            OWNCLOUD_DOMAIN: dir.noyu.cf
            OWNCLOUD_DB_TYPE: mysql
            OWNCLOUD_DB_HOST: owncloud-db
            OWNCLOUD_DB_NAME: owncloud
            OWNCLOUD_DB_USERNAME: owncloud
            OWNCLOUD_DB_PASSWORD: ${OWNCLOUD_DB_PASSWORD}
            OWNCLOUD_REDIS_ENABLED: "true"
            OWNCLOUD_REDIS_HOST: redis
            OWNCLOUD_ADMIN_USERNAME: noyuno
            OWNCLOUD_ADMIN_PASSWORD: ${OWNCLOUD_PASSWORD}
        volumes:
            - ./data/owncloud/data:/mnt/data

    owncloud-db:
        image: mariadb:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${OWNCLOUD_DB_PASSWORD}
            MYSQL_USER: owncloud
            MYSQL_PASSWORD: ${OWNCLOUD_DB_PASSWORD}
            MYSQL_DATABASE: owncloud
        volumes:
            - ./data/owncloud/mariadb:/var/lib/mysql
            - ./data/owncloud/mariadb-backup:/var/lib/backup

    redis:
        image: redis:alpine
        restart: always

    wekan:
        image: quay.io/wekan/wekan:latest
        restart: always
        links:
            - wekan-db
        environment:
            ROOT_URL: https://board.noyu.cf
            MONGO_URL: mongodb://wekan-db:27017/wekan
            WITH_API: "true"
    
    wekan-db:
        image: mongo:latest
        restart: always
        expose:
            - 27017
        command: mongod --smallfiles --oplogSize 128
        volumes:
            - ./data/wekan/mongodb:/data/db
            - ./data/wekan/mongodb-dump:/dump

