version: "3"
services:
    https-portal:
        image: steveltn/https-portal:1
        restart: always
        links:
            - nginx
        ports:
            - '80:80'
            - '443:443'
        environment:
            STAGE: staging
            DOMAINS: 'k2.noyu.cf -> http://nginx:80'
        volumes:
            - cert:/var/lib/https-portal
            - vhosts:/var/www/cert
    gitbucket:
        image: gitbucket/gitbucket
        restart: always
        volumes:
            - gitbucket:/gitbucket
        depends_on:
            - postgres
        environment:
            GITBUCKET_DB_URL: 'jdbc:postgresql://postgres/gitbucket'
            GITBUCKET_DB_USER: gitbucket
            GITBUCKET_DB_PASSWORD: ${POSTGRES_GITBUCKET_PASSWORD}
        
    postgres:
        image: postgres:11-alpine
        restart: always
        volumes:
            - /var/data/postgres:/var/lib/postgresql/data
            - ./postgres/init:/docker-entrypoint-initdb.d
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_GITBUCKET_PASSWORD: ${POSTGRES_GITBUCKET_PASSWORD}

#    nginx:
#        build: nginx
#        restart: always
#        ports:
#            - 80:80
#        volumes:
#            - cert:/var/lib/cert

    nginx:
        build: nginx.notls
        restart: always
        ports:
            - 80:80
        volumes:
            - cert:/var/lib/cert

    unbound:
        build: unbound
        ports:
            - 53:53

volumes:
    cert:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /var/data/cert
    vhosts:
    gitbucket:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /var/data/gitbucket


