version: "3"
services:
    nginx:
        image: steveltn/https-portal:1
        links:
            - php7
            - gitbucket
            - minio
            - wekan
        ports:
            - 80:80
            - 443:443
        restart: always
        environment:
            STAGE: staging
            DOMAINS: |
                noyu.cf
                k2.noyu.cf
                git.noyu.cf -> http://gitbucket:8080
                s3.noyu.cf -> http://minio:9000
                board.noyu.cf -> http://wekan:8080
                ci.noyu.cf -> http://jenkins:8080
                job.noyu.cf -> http://rundeck:4443
            SERVER_NAMES_HASH_BUCKET_SIZE: 64
        volumes:
            - ./data/cert:/var/lib/https-portal
            - ./nginx/conf:/var/lib/nginx-conf:ro
            - ./nginx/html:/var/www/vhosts

    php7:
        image: php:7-fpm-alpine
        restart: always
        volumes:
            - ./nginx/html:/var/www/html

    gitbucket:
        image: gitbucket/gitbucket
        restart: always
        volumes:
            - ./data/gitbucket/data:/gitbucket
        links:
            - gitbucket-db
        environment:
            GITBUCKET_DB_URL: 'jdbc:postgresql://gitbucket-postgres/gitbucket'
            GITBUCKET_DB_USER: gitbucket
            GITBUCKET_DB_PASSWORD: ${GITBUCKET_DB_PASSWORD}

    gitbucket-db:
        build: gitbucket/postgres
        restart: always
        volumes:
            - ./data/gitbucket/postgres:/var/lib/postgresql/data
            - ./gitbucket/postgres/init:/docker-entrypoint-initdb.d
        environment:
            POSTGRES_USER: postgres
            DB_PASSWORD: ${GITBUCKET_DB_PASSWORD}

    minio:
        image: minio/minio:latest
        volumes:
            - ./data/minio/1:/data
        environment:
            MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
            MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
        command: server /data

    wekan:
        image: quay.io/wekan/wekan:latest
        restart: always
        links:
            - wekan-db
        environment:
            ROOT_URL: https://board.noyu.cf
            MONGO_URL: mongodb://wekan-db:27017/wekan
            WITH_API: "true"

    wekan-db:
        image: mongo:latest
        restart: always
        expose:
            - 27017
        command: mongod --smallfiles --oplogSize 128
        volumes:
            - ./data/wekan/mongodb:/data/db
            - ./data/wekan/mongodb-dump:/dump

    rundeck:
        build: jordan/rundeck:latest
        environment:
            EXTERNAL_SERVER_URL: https://job.noyu.cf
            RUNDECK_ADMIN_PASSWORD: ${RUNDECK_ADMIN_PASSWORD}
            

    anime:
        build: anime
        restart: always
        volumes:
            - ./data/anime:/data

    notifyd:
        build: ./notifyd
        restart: always
        volumes:
            - ./data/notifyd:/data

