version: "3"
services:
    https-portal:
        image: steveltn/https-portal:1
#        restart: always
#        links:
#            - nginx
        environment:
            STAGE: staging
            DOMAINS: 'noyu.cf, k2.noyu.cf, git.noyu.cf, dir.noyu.cf'
        volumes:
            - ./data/cert:/var/lib/https-portal
            - certchallenges:/var/www/default/challenges
    gitbucket:
        image: gitbucket/gitbucket
        restart: always
        volumes:
            - ./data/gitbucket:/gitbucket
        depends_on:
            - postgres
        environment:
            GITBUCKET_DB_URL: 'jdbc:postgresql://postgres/gitbucket'
            GITBUCKET_DB_USER: gitbucket
            GITBUCKET_DB_PASSWORD: ${POSTGRES_GITBUCKET_PASSWORD}
        
    postgres:
        image: postgres:11-alpine
        restart: always
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
            - ./postgres/init:/docker-entrypoint-initdb.d
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_GITBUCKET_PASSWORD: ${POSTGRES_GITBUCKET_PASSWORD}

    nginx:
        build: nginx
        restart: always
        ports:
            - 80:80
        volumes:
            - ./data/cert:/var/lib/cert
            - ./nginx/www:/var/www/html
            - certchallenges:/var/www/cert

    nginx-notls:
        build: nginx.notls
        restart: always
        ports:
            - 80:80
        volumes:
            - ./data/cert:/var/lib/cert
            - ./nginx/www:/var/www/html
            - certchallenges:/var/www/cert

#    unbound:
#        build: unbound
#        ports:
#            - 53:53

volumes:
#    cert:
#        driver: local
#        driver_opts:
#            type: none
#            o: bind
#            device: /home/noyuno/k2/data/cert
    certchallenges:


