version: "3"
services:
    nginx:
        image: steveltn/https-portal:1
        links:
            - php7
        ports:
            - 80:80
            - 443:443
#        restart: always
        environment:
            STAGE: staging
            DOMAINS: 'noyu.cf, k2.noyu.cf, git.noyu.cf, dir.noyu.cf'
        volumes:
            - ./data/cert:/var/lib/https-portal
            - ./nginx/conf:/var/lib/nginx-conf
            - ./nginx/html:/var/www/html
    php7:
        image: php:7-fpm-alpine
        volumes:
            - ./nginx/html:/var/www/html
    gitbucket:
        image: gitbucket/gitbucket
        restart: always
        volumes:
            - ./data/gitbucket:/gitbucket
        depends_on:
            - postgres
        environment:
            GITBUCKET_DB_URL: 'jdbc:postgresql://postgres/gitbucket'
            GITBUCKET_DB_USER: gitbucket
            GITBUCKET_DB_PASSWORD: ${POSTGRES_GITBUCKET_PASSWORD}
        
    postgres:
        image: postgres:11-alpine
        restart: always
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
            - ./postgres/init:/docker-entrypoint-initdb.d
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_GITBUCKET_PASSWORD: ${POSTGRES_GITBUCKET_PASSWORD}

#    nginx:
#        build: nginx
#        restart: always
#        ports:
#            - 80:80
#        volumes:
#            - ./data/cert:/var/lib/cert
#            - ./nginx/www:/var/www/html
#            - certchallenges:/var/www/cert
#
#    nginx-notls:
#        build: nginx-notls
#        restart: always
#        ports:
#            - 80:80
#        volumes:
#            - ./data/cert:/var/lib/cert
#            - ./nginx-notls/www:/var/www/html
#            - certchallenges:/var/www/cert

#    unbound:
#        build: unbound
#        ports:
#            - 53:53

#volumes:
#    cert:
#        driver: local
#        driver_opts:
#            type: none
#            o: bind
#            device: /home/noyuno/k2/data/cert
#    certchallenges:


