version: "3"
services:
    https-portal:
        image: steveltn/https-portal:1
        restart: always
        links:
            - nginx
        ports:
            - '80:80'
            - '443:443'
        environment:
            STAGE: staging
            DOMAINS: 'k2.noyuno.space -> http://nginx:80'
        volumes:
            - ./data/cert:/var/lib/https-portal
            - vhosts:/var/www/cert
    gitbucket:
        image: gitbucket/gitbucket
        restart: always
        volumes:
            - ./data/gitbucket:/gitbucket
        depends_on:
            - postgres
        environment:
            GITBUCKET_DB_URL: 'jdbc:postgresql://postgres/gitbucket'
            GITBUCKET_DB_USER: gitbucket
            GITBUCKET_DB_PASSWORD: ${POSTGRES_GITBUCKET_PASSWORD}
        
    postgres:
        build: postgres
        restart: always
        volumes:
            - /var/data/postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_GITBUCKET_PASSWORD: ${POSTGRES_GITBUCKET_PASSWORD}
    nginx:
        build: nginx

volumes:
    vhosts:


