version: "3"
services:
    nginx:
        image: steveltn/https-portal:1
        links:
            - php7
            - gitbucket
            - minio
            - wekan
            - notifyd
        ports:
            - 80:80
            - 443:443
        restart: always
        environment:
            STAGE: staging
            DOMAINS: |
                noyu.cf
                k2.noyu.cf
                git.noyu.cf -> http://gitbucket:8080
                s3.noyu.cf -> http://minio:9000
                board.noyu.cf -> http://wekan:8080
                ci.noyu.cf -> http://jenkins:8080
                job.noyu.cf -> http://rundeck:4443
                anime.noyu.cf
                notify.noyu.cf -> http;//notifyd:4000
            SERVER_NAMES_HASH_BUCKET_SIZE: 64
        volumes:
            - ./data/cert:/var/lib/https-portal
            - ./nginx:/var/lib/nginx-conf:ro
            - ./html:/var/www/vhosts
            - ./animed/html:/var/www/vhosts/anime.noyu.cf
            - ./data/animed:/var/www/vhosts/anime.noyu.cf/data

    php7:
        image: php:7-fpm-alpine
        restart: always
        volumes:
            - ./nginx/html:/var/www/html

    gitbucket:
        image: gitbucket/gitbucket:latest
        restart: always
        volumes:
            - ./data/gitbucket/data:/gitbucket
        links:
            - gitbucket-db
        environment:
            GITBUCKET_DB_URL: 'jdbc:postgresql://gitbucket-db/gitbucket'
            GITBUCKET_DB_USER: gitbucket
            GITBUCKET_DB_PASSWORD: ${GITBUCKET_DB_PASSWORD}

    gitbucket-db:
        image: postgres:11-alpine
        restart: always
        environment:
            POSTGRES_USER: gitbucket
            POSTGRES_PASSWORD: ${GITBUCKET_DB_PASSWORD}
        volumes:
            - ./data/gitbucket/postgres:/var/lib/postgresql/data

    minio:
        image: minio/minio:latest
        environment:
            MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
            MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
        command: server /data
        volumes:
            - ./data/minio/1:/data

    wekan:
        image: quay.io/wekan/wekan:latest
        restart: always
        links:
            - wekan-db
        environment:
            ROOT_URL: https://board.noyu.cf
            MONGO_URL: mongodb://wekan-db:27017/wekan
            WITH_API: "true"

    wekan-db:
        image: mongo:latest
        restart: always
        expose:
            - 27017
        command: mongod --smallfiles --oplogSize 128
        volumes:
            - ./data/wekan/mongodb:/data/db
            - ./data/wekan/mongodb-dump:/dump

    rundeck:
        image: jordan/rundeck:latest
        environment:
            EXTERNAL_SERVER_URL: https://job.noyu.cf
            RUNDECK_ADMIN_PASSWORD: ${RUNDECK_ADMIN_PASSWORD}

    animed:
        build: animed
        restart: always
        volumes:
            - ./data/animed:/data

    notifyd:
        build: go/src/notifyd
        links:
            - notifyd-db
        environment:
            NOTIFYD_PATH: /go/src/notifyd
            NOTIFYD_DATA: /data/notifyd
            NOTIFYD_DB_HOST: notifyd-db
            NOTIFYD_DB_USER: notifyd
            NOTIFYD_DB_PASSWORD: ${NOTIFYD_DB_PASSWORD}
            NOTIFYD_APP_SECRET: ${NOTIFYD_APP_SECRET}
            HOSTNAME: notify.noyu.cf
            PORT: 9000
            GOPATH: /go
        volumes:
            - ./go/src/notifyd:/go/src/notifyd
            - ./data/notifyd/data:/data/notifyd

    notifyd-db:
        image: postgres:11-alpine
        restart: always
        environment:
            POSTGRES_USER: notifyd
            POSTGRES_PASSWORD: ${NOTIFYD_DB_PASSWORD}
        volumes:
            - ./data/notifyd/postgres:/var/lib/postgresql/data

    concourse:
        image: concourse/concourse
        command: quickstart
        privileged: true
        links: 
            - concourse-db
        ports: 
            - 8080:8080
        environment:
            CONCOURSE_POSTGRES_HOST: concourse-db
            CONCOURSE_POSTGRES_USER: concourse
            CONCOURSE_POSTGRES_PASSWORD: ${CONCOURSE_DB_PASSWORD}
            CONCOURSE_POSTGRES_DATABASE: concourse

    concourse-db:
        image: postgres:11-alpine
        restart: always
        environment:
            POSTGRES_USER: concourse
            POSTGRES_PASSWORD: concourse_pass
        volumes:
            - ./data/concourse/postgres:/var/lib/postgresql/data

    squid:
        build: squid
        restart: always
        ports:
            - 3128:3128

