version: "3"
services:
                
    pe-client:
        build: .
        restart: "on-failure:5"
        environment:
            PE_TOKEN: "${PE_TOKEN}"
        volumes:
            - C:\Users\noyuno\Desktop\tmp:/data
            - .:/opt/pec
        privileged: "true"