version: "3"
services:
    pe:
        build: .
        restart: "on-failure:5"
        ports:
            - "3000:3000"
        environment:
            DISCORDBOT: discordbot
            DISCORDBOT_TOKEN: "${DISCORDBOT_TOKEN}"
            PE_TOKEN: "${PE_TOKEN}"
            NODE_ENV: development
        volumes:
            - C:\Users\noyuno\Desktop\pe-tmp:/data
            - ./routes:/opt/pe/routes:ro
            - ./public:/opt/pe/public
            - ./sass:/opt/pe/sass:ro
            - ./views:/opt/pe/views:ro
            - ./src:/opt/pe/src:ro
